Aim: Dep upon the #hours studied , #hours slept, IQ, loc   --->predict maks

Solution:

In [156]:
import numpy as np
import pandas as pd

In [157]:
import sklearn

In [158]:
# Here we are making an data Frame randomly.
from numpy.random import rand

df  = pd.DataFrame(rand( 50 , 3)*10, columns = 'Hours_studied Hours_slept iQ '.split())
df.head()

   Hours_studied  Hours_slept        iQ
0       0.352498     3.714741  4.008902
1       5.248383     8.645533  1.787283
2       5.600024     2.155584  2.727096
3       0.101538     1.219933  3.371587
4       6.320626     7.845795  8.297170

In [159]:
# Here we are adding column called location.
from random import choice

location = []
for i in range(50):
    
    location.append(choice(["Hyderabad" , "Khammam" , "Warangal","Delhi"]))
 

df['Location'] = location

df.head()

   Hours_studied  Hours_slept        iQ   Location
0       0.352498     3.714741  4.008902   Warangal
1       5.248383     8.645533  1.787283  Hyderabad
2       5.600024     2.155584  2.727096   Warangal
3       0.101538     1.219933  3.371587  Hyderabad
4       6.320626     7.845795  8.297170      Delhi

In [160]:
# Here we are adding Marks column to the dataframe Which is created before.
df['Marks'] = (1.73 + (3.34*df['Hours_studied'])
                    + (2.45*df['Hours_slept'])
                    + (1.83*df['iQ']  ))
df['Marks'] =  df['Marks'] +np.random.rand(50)*20
               
df.to_csv('Students.csv',index=False)

In [161]:
df.head()

   Hours_studied  Hours_slept        iQ   Location      Marks
0       0.352498     3.714741  4.008902   Warangal  38.333004
1       5.248383     8.645533  1.787283  Hyderabad  55.017760
2       5.600024     2.155584  2.727096   Warangal  42.889849
3       0.101538     1.219933  3.371587  Hyderabad  19.865350
4       6.320626     7.845795  8.297170      Delhi  75.215463

In [162]:
# Here we are importing the data set.
dataset = pd.read_csv('Students.csv')

X = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:,-1].values
print(y)

[38.33 55.02 42.89 19.87 75.22 51.06 30.35 68.69 35.33 43.68 39.94 45.07
 52.56 48.28 19.73 73.27 49.4  34.17 32.34 41.86 60.7  40.05 40.69 26.13
 53.04 51.62 59.86 63.27 60.15 51.2  59.02 29.87 76.87 53.68 57.72 47.5
 54.99 60.78 54.2  39.57 56.64 50.34 49.58 28.05 77.12 36.17 54.78 20.5
 36.69 56.76]

In [163]:
print(X)

[[0.3524979543650364 3.71474136646237 4.008902237262562 'Warangal']
 [5.248383195234921 8.64553341884594 1.7872831861582228 'Hyderabad']
 [5.600023755892716 2.1555839763815654 2.7270960398118618 'Warangal']
 [0.1015384411175923 1.219932777287429 3.371587255939552 'Hyderabad']
 [6.320625609742639 7.845794533158949 8.297169602222828 'Delhi']
 [1.3826434006566646 9.480287842370853 1.8858793532479456 'Warangal']
 [1.214042780423065 2.489647978501879 5.321152911817558 'Warangal']
 [9.234325483711132 5.357505290824499 1.8853605603562584 'Hyderabad']
 [3.665516373896848 0.0323249432272909 5.772368144276983 'Hyderabad']
 [5.8239735695966255 6.2303822558762665 2.0546956972123374 'Khammam']
 [7.591660224003867 0.6454231893472939 4.116217762000169 'Khammam']
 [2.6999450244144017 7.322580044543087 6.211197947294005 'Warangal']
 [0.532432754495481 9.207765249521987 8.824125707307847 'Khammam']
 [9.14798999006231 1.685595729906607 0.2250745887663097 'Hyderabad']
 [0.9001688192435175 1.6757386980171065 1.2339055510472474 'Warangal']
 [7.849846130290188 7.961429608741123 8.022486921055913 'Hyderabad']
 [3.1886954861782657 5.840689935836364 9.762212364479623 'Hyderabad']
 [5.547913731527922 1.108175612272747 5.2857421235658215 'Delhi']
 [5.290291673521827 0.0702361231249459 5.882838197280323 'Warangal']
 [6.012415422180459 0.6203069602168998 7.512738746285706 'Khammam']
 [8.584614846431379 1.08662352939094 4.20736970622852 'Warangal']
 [0.3122598828481504 8.445307138486315 2.892330046626705 'Warangal']
 [4.88436612477707 4.73310357080314 0.7816646187954068 'Khammam']
 [2.0654298720064435 3.1728295804434667 3.720514109971247 'Warangal']
 [7.548261139586555 0.757685040050099 2.753208882285574 'Delhi']
 [1.9202143103326248 5.391065789748009 7.2705657785322035 'Warangal']
 [8.094159544023437 5.554143017030391 9.215019614444792 'Hyderabad']
 [7.290669523949108 2.2494863983380533 9.344141097639586 'Hyderabad']
 [4.582257290357571 5.116979264401676 6.492616101606488 'Warangal']
 [8.611399164327905 1.9044090789751469 3.166977251099924 'Delhi']
 [6.853534640242101 0.5028700598639468 8.566643042610368 'Warangal']
 [5.517053769938922 0.6810105809493305 2.387271255950365 'Hyderabad']
 [8.906190059540101 5.93250600768049 7.163068385634489 'Hyderabad']
 [7.163343239161236 4.50549308396498 3.5088385651002407 'Khammam']
 [6.939119845601227 1.9446582243118429 5.300765102699456 'Hyderabad']
 [0.0804736131837879 7.601973120965906 9.136874305659829 'Khammam']
 [6.969502449166707 3.230483666222571 9.379631439501887 'Warangal']
 [7.948504694850066 2.9570721316091184 9.978864764298526 'Khammam']
 [3.2486823617999336 8.700081380807534 9.831300409415784 'Khammam']
 [3.4000024997009715 7.028693645046644 4.508130708852543 'Delhi']
 [5.025869469891048 9.142375845701253 5.260730741710699 'Hyderabad']
 [2.3533174010959703 8.261737176493314 0.6538601848094916 'Khammam']
 [4.47124600308478 9.934214535339596 3.0962780285505 'Warangal']
 [0.3379255667756209 5.331381156313007 3.7788994088127774 'Delhi']
 [7.64367973953794 8.335465257526328 7.464370979820865 'Hyderabad']
 [2.717800750478178 2.9447317641868254 7.721818118083883 'Delhi']
 [2.2549195642722584 8.436086115428218 6.301305723500237 'Khammam']
 [0.5071675835831002 5.561100477838107 1.7514400013455875 'Delhi']
 [2.914224462055326 0.1262842257466212 5.379538015543066 'Delhi']
 [7.8764705452305295 3.892360539759933 6.565246940596468 'Khammam']]

In [164]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])],  remainder='passthrough')
print(ct)

X = np.array(ct.fit_transform(X))

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [3])])

In [165]:
print(X)

[[0.0 0.0 0.0 1.0 0.3524979543650364 3.71474136646237 4.008902237262562]
 [0.0 1.0 0.0 0.0 5.248383195234921 8.64553341884594 1.7872831861582228]
 [0.0 0.0 0.0 1.0 5.600023755892716 2.1555839763815654 2.7270960398118618]
 [0.0 1.0 0.0 0.0 0.1015384411175923 1.219932777287429 3.371587255939552]
 [1.0 0.0 0.0 0.0 6.320625609742639 7.845794533158949 8.297169602222828]
 [0.0 0.0 0.0 1.0 1.3826434006566646 9.480287842370853 1.8858793532479456]
 [0.0 0.0 0.0 1.0 1.214042780423065 2.489647978501879 5.321152911817558]
 [0.0 1.0 0.0 0.0 9.234325483711132 5.357505290824499 1.8853605603562584]
 [0.0 1.0 0.0 0.0 3.665516373896848 0.0323249432272909 5.772368144276983]
 [0.0 0.0 1.0 0.0 5.8239735695966255 6.2303822558762665
  2.0546956972123374]
 [0.0 0.0 1.0 0.0 7.591660224003867 0.6454231893472939 4.116217762000169]
 [0.0 0.0 0.0 1.0 2.6999450244144017 7.322580044543087 6.211197947294005]
 [0.0 0.0 1.0 0.0 0.532432754495481 9.207765249521987 8.824125707307847]
 [0.0 1.0 0.0 0.0 9.14798999006231 1.685595729906607 0.2250745887663097]
 [0.0 0.0 0.0 1.0 0.9001688192435175 1.6757386980171065
  1.2339055510472474]
 [0.0 1.0 0.0 0.0 7.849846130290188 7.961429608741123 8.022486921055913]
 [0.0 1.0 0.0 0.0 3.1886954861782657 5.840689935836364 9.762212364479623]
 [1.0 0.0 0.0 0.0 5.547913731527922 1.108175612272747 5.2857421235658215]
 [0.0 0.0 0.0 1.0 5.290291673521827 0.0702361231249459 5.882838197280323]
 [0.0 0.0 1.0 0.0 6.012415422180459 0.6203069602168998 7.512738746285706]
 [0.0 0.0 0.0 1.0 8.584614846431379 1.08662352939094 4.20736970622852]
 [0.0 0.0 0.0 1.0 0.3122598828481504 8.445307138486315 2.892330046626705]
 [0.0 0.0 1.0 0.0 4.88436612477707 4.73310357080314 0.7816646187954068]
 [0.0 0.0 0.0 1.0 2.0654298720064435 3.1728295804434667 3.720514109971247]
 [1.0 0.0 0.0 0.0 7.548261139586555 0.757685040050099 2.753208882285574]
 [0.0 0.0 0.0 1.0 1.9202143103326248 5.391065789748009 7.2705657785322035]
 [0.0 1.0 0.0 0.0 8.094159544023437 5.554143017030391 9.215019614444792]
 [0.0 1.0 0.0 0.0 7.290669523949108 2.2494863983380533 9.344141097639586]
 [0.0 0.0 0.0 1.0 4.582257290357571 5.116979264401676 6.492616101606488]
 [1.0 0.0 0.0 0.0 8.611399164327905 1.9044090789751469 3.166977251099924]
 [0.0 0.0 0.0 1.0 6.853534640242101 0.5028700598639468 8.566643042610368]
 [0.0 1.0 0.0 0.0 5.517053769938922 0.6810105809493305 2.387271255950365]
 [0.0 1.0 0.0 0.0 8.906190059540101 5.93250600768049 7.163068385634489]
 [0.0 0.0 1.0 0.0 7.163343239161236 4.50549308396498 3.5088385651002407]
 [0.0 1.0 0.0 0.0 6.939119845601227 1.9446582243118429 5.300765102699456]
 [0.0 0.0 1.0 0.0 0.0804736131837879 7.601973120965906 9.136874305659829]
 [0.0 0.0 0.0 1.0 6.969502449166707 3.230483666222571 9.379631439501887]
 [0.0 0.0 1.0 0.0 7.948504694850066 2.9570721316091184 9.978864764298526]
 [0.0 0.0 1.0 0.0 3.2486823617999336 8.700081380807534 9.831300409415784]
 [1.0 0.0 0.0 0.0 3.4000024997009715 7.028693645046644 4.508130708852543]
 [0.0 1.0 0.0 0.0 5.025869469891048 9.142375845701253 5.260730741710699]
 [0.0 0.0 1.0 0.0 2.3533174010959703 8.261737176493314 0.6538601848094916]
 [0.0 0.0 0.0 1.0 4.47124600308478 9.934214535339596 3.0962780285505]
 [1.0 0.0 0.0 0.0 0.3379255667756209 5.331381156313007 3.7788994088127774]
 [0.0 1.0 0.0 0.0 7.64367973953794 8.335465257526328 7.464370979820865]
 [1.0 0.0 0.0 0.0 2.717800750478178 2.9447317641868254 7.721818118083883]
 [0.0 0.0 1.0 0.0 2.2549195642722584 8.436086115428218 6.301305723500237]
 [1.0 0.0 0.0 0.0 0.5071675835831002 5.561100477838107 1.7514400013455875]
 [1.0 0.0 0.0 0.0 2.914224462055326 0.1262842257466212 5.379538015543066]
 [0.0 0.0 1.0 0.0 7.8764705452305295 3.892360539759933 6.565246940596468]]

In [166]:
print(y)

[38.33 55.02 42.89 19.87 75.22 51.06 30.35 68.69 35.33 43.68 39.94 45.07
 52.56 48.28 19.73 73.27 49.4  34.17 32.34 41.86 60.7  40.05 40.69 26.13
 53.04 51.62 59.86 63.27 60.15 51.2  59.02 29.87 76.87 53.68 57.72 47.5
 54.99 60.78 54.2  39.57 56.64 50.34 49.58 28.05 77.12 36.17 54.78 20.5
 36.69 56.76]

In [167]:
# Splitting the dataset into Training set and Test set.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train , y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(y_test)

[60.15 45.07 39.94 50.34 42.89 63.27 54.2  29.87 40.69 75.22]

In [168]:
print(y_train)

[53.68 47.5  59.86 57.72 32.34 68.69 19.73 36.17 36.69 51.2  73.27 59.02
 76.87 49.4  49.58 60.7  28.05 35.33 48.28 51.62 51.06 34.17 56.64 56.76
 55.02 52.56 60.78 53.04 30.35 26.13 54.99 40.05 41.86 43.68 39.57 54.78
 19.87 38.33 20.5  77.12]

In [169]:
print(X_train)

[[0.0 0.0 1.0 0.0 7.163343239161236 4.50549308396498 3.5088385651002407]
 [0.0 0.0 1.0 0.0 0.0804736131837879 7.601973120965906 9.136874305659829]
 [0.0 1.0 0.0 0.0 8.094159544023437 5.554143017030391 9.215019614444792]
 [0.0 1.0 0.0 0.0 6.939119845601227 1.9446582243118429 5.300765102699456]
 [0.0 0.0 0.0 1.0 5.290291673521827 0.0702361231249459 5.882838197280323]
 [0.0 1.0 0.0 0.0 9.234325483711132 5.357505290824499 1.8853605603562584]
 [0.0 0.0 0.0 1.0 0.9001688192435175 1.6757386980171065
  1.2339055510472474]
 [1.0 0.0 0.0 0.0 2.717800750478178 2.9447317641868254 7.721818118083883]
 [1.0 0.0 0.0 0.0 2.914224462055326 0.1262842257466212 5.379538015543066]
 [1.0 0.0 0.0 0.0 8.611399164327905 1.9044090789751469 3.166977251099924]
 [0.0 1.0 0.0 0.0 7.849846130290188 7.961429608741123 8.022486921055913]
 [0.0 0.0 0.0 1.0 6.853534640242101 0.5028700598639468 8.566643042610368]
 [0.0 1.0 0.0 0.0 8.906190059540101 5.93250600768049 7.163068385634489]
 [0.0 1.0 0.0 0.0 3.1886954861782657 5.840689935836364 9.762212364479623]
 [0.0 0.0 0.0 1.0 4.47124600308478 9.934214535339596 3.0962780285505]
 [0.0 0.0 0.0 1.0 8.584614846431379 1.08662352939094 4.20736970622852]
 [1.0 0.0 0.0 0.0 0.3379255667756209 5.331381156313007 3.7788994088127774]
 [0.0 1.0 0.0 0.0 3.665516373896848 0.0323249432272909 5.772368144276983]
 [0.0 1.0 0.0 0.0 9.14798999006231 1.685595729906607 0.2250745887663097]
 [0.0 0.0 0.0 1.0 1.9202143103326248 5.391065789748009 7.2705657785322035]
 [0.0 0.0 0.0 1.0 1.3826434006566646 9.480287842370853 1.8858793532479456]
 [1.0 0.0 0.0 0.0 5.547913731527922 1.108175612272747 5.2857421235658215]
 [0.0 1.0 0.0 0.0 5.025869469891048 9.142375845701253 5.260730741710699]
 [0.0 0.0 1.0 0.0 7.8764705452305295 3.892360539759933 6.565246940596468]
 [0.0 1.0 0.0 0.0 5.248383195234921 8.64553341884594 1.7872831861582228]
 [0.0 0.0 1.0 0.0 0.532432754495481 9.207765249521987 8.824125707307847]
 [0.0 0.0 1.0 0.0 7.948504694850066 2.9570721316091184 9.978864764298526]
 [1.0 0.0 0.0 0.0 7.548261139586555 0.757685040050099 2.753208882285574]
 [0.0 0.0 0.0 1.0 1.214042780423065 2.489647978501879 5.321152911817558]
 [0.0 0.0 0.0 1.0 2.0654298720064435 3.1728295804434667 3.720514109971247]
 [0.0 0.0 0.0 1.0 6.969502449166707 3.230483666222571 9.379631439501887]
 [0.0 0.0 0.0 1.0 0.3122598828481504 8.445307138486315 2.892330046626705]
 [0.0 0.0 1.0 0.0 6.012415422180459 0.6203069602168998 7.512738746285706]
 [0.0 0.0 1.0 0.0 5.8239735695966255 6.2303822558762665
  2.0546956972123374]
 [1.0 0.0 0.0 0.0 3.4000024997009715 7.028693645046644 4.508130708852543]
 [0.0 0.0 1.0 0.0 2.2549195642722584 8.436086115428218 6.301305723500237]
 [0.0 1.0 0.0 0.0 0.1015384411175923 1.219932777287429 3.371587255939552]
 [0.0 0.0 0.0 1.0 0.3524979543650364 3.71474136646237 4.008902237262562]
 [1.0 0.0 0.0 0.0 0.5071675835831002 5.561100477838107 1.7514400013455875]
 [0.0 1.0 0.0 0.0 7.64367973953794 8.335465257526328 7.464370979820865]]

In [170]:
print(X_test)

[[0.0 0.0 0.0 1.0 4.582257290357571 5.116979264401676 6.492616101606488]
 [0.0 0.0 0.0 1.0 2.6999450244144017 7.322580044543087 6.211197947294005]
 [0.0 0.0 1.0 0.0 7.591660224003867 0.6454231893472939 4.116217762000169]
 [0.0 0.0 1.0 0.0 2.3533174010959703 8.261737176493314 0.6538601848094916]
 [0.0 0.0 0.0 1.0 5.600023755892716 2.1555839763815654 2.7270960398118618]
 [0.0 1.0 0.0 0.0 7.290669523949108 2.2494863983380533 9.344141097639586]
 [0.0 0.0 1.0 0.0 3.2486823617999336 8.700081380807534 9.831300409415784]
 [0.0 1.0 0.0 0.0 5.517053769938922 0.6810105809493305 2.387271255950365]
 [0.0 0.0 1.0 0.0 4.88436612477707 4.73310357080314 0.7816646187954068]
 [1.0 0.0 0.0 0.0 6.320625609742639 7.845794533158949 8.297169602222828]]

In [171]:
# we are training the linear Regression model on the Training set.
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [172]:
# Predicting the Results
y_pred = regressor.predict(X_test)

np.set_printoptions(precision=2)
print("\n\n\nPredicted  Actual")
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

Predicted  Actual
[[52.29 60.15]
 [50.17 45.07]
 [46.73 39.94]
 [40.25 50.34]
 [43.31 42.89]
 [59.43 63.27]
 [58.51 54.2 ]
 [38.66 29.87]
 [41.39 40.69]
 [63.41 75.22]]

In [173]:
np.set_printoptions(precision=2)
print(np.concatenate((X_test ,y_pred.reshape(len(y_pred),1) ,y_test.reshape(len(y_test),1)) ,1))

[[0.0 0.0 0.0 1.0 4.582257290357571 5.116979264401676 6.492616101606488
  52.292274295560716 60.15156667166399]
 [0.0 0.0 0.0 1.0 2.6999450244144017 7.322580044543087 6.211197947294005
  50.171149276392384 45.071369461410825]
 [0.0 0.0 1.0 0.0 7.591660224003867 0.6454231893472939 4.116217762000169
  46.73282775668285 39.94427461377357]
 [0.0 0.0 1.0 0.0 2.3533174010959703 8.261737176493314 0.6538601848094916
  40.24584724280719 50.33552954212598]
 [0.0 0.0 0.0 1.0 5.600023755892716 2.1555839763815654 2.7270960398118618
  43.31380800591953 42.889849081469386]
 [0.0 1.0 0.0 0.0 7.290669523949108 2.2494863983380533 9.344141097639586
  59.4304061318831 63.2732278604924]
 [0.0 0.0 1.0 0.0 3.2486823617999336 8.700081380807534 9.831300409415784
  58.50540997499023 54.19860371077599]
 [0.0 1.0 0.0 0.0 5.517053769938922 0.6810105809493305 2.387271255950365
  38.66161350959081 29.866115621784218]
 [0.0 0.0 1.0 0.0 4.88436612477707 4.73310357080314 0.7816646187954068
  41.389484966463996 40.69174626468579]
 [1.0 0.0 0.0 0.0 6.320625609742639 7.845794533158949 8.297169602222828
  63.40688410868199 75.21546273850434]]

In [174]:
len(y_pred) # length of the pridected values.

10

In [175]:
y_test # Data used to test the model.

array([60.15, 45.07, 39.94, 50.34, 42.89, 63.27, 54.2 , 29.87, 40.69,
       75.22])

In [176]:
y_pred # These are the pridect values from.

array([52.29, 50.17, 46.73, 40.25, 43.31, 59.43, 58.51, 38.66, 41.39,
       63.41])